[package]
name = "FlixBox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "0.9.2"
gdk = "0.13.2"
gdk-pixbuf = "0.9.0"
#gstreamer = "0.18"
